action_id: trunk-cache-prune
date: 2026-05-07 15:53:20
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 0
  out: ""
  err: ""
timestamp: 1778169200
full_timestamp:
  nanos: 775380000
  seconds: 1778169200
trunk_version: 1.25.0
