@echo off
REM Generated by trunk tool 'checkov'
set VIRTUAL_ENV=C:\Users\AKSHAY\AppData\Local\trunk\tools\checkov\3.2.526-6df5cb77cf8bbd541a0f443261f76631
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\AKSHAY\AppData\Local\trunk\tools\checkov\3.2.526-6df5cb77cf8bbd541a0f443261f76631/bin;C:\Users\AKSHAY\AppData\Local\trunk\tools\checkov\3.2.526-6df5cb77cf8bbd541a0f443261f76631/Scripts;C:\Users\AKSHAY\AppData\Local\trunk\tools\python\3.14.4-cb3a144a569cdde1b1583669bb421ff0/bin;C:\Users\AKSHAY\AppData\Local\trunk\tools\python\3.14.4-cb3a144a569cdde1b1583669bb421ff0;C:\Users\AKSHAY\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\AKSHAY\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set PYTHONUTF8=1

start /w /b checkov %*
