@echo off
REM Generated by trunk tool 'grype'
set PATH=C:\Users\AKSHAY\AppData\Local\trunk\tools\grype\0.112.0-c96339754454d289a73b4396ee953ddf;C:\Users\AKSHAY\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\AKSHAY\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b grype %*
