@echo off
REM Generated by trunk tool 'osv-scanner'
set PATH=C:\Users\AKSHAY\AppData\Local\trunk\tools\osv-scanner\2.3.6-72eb9340dc81c79daa5fd66d5530493e;C:\Users\AKSHAY\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\AKSHAY\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b osv-scanner %*
